### ISSUE TITLE
Preprocessing error and request for PG database. 

### ISSUE THREAD

**Issue by GenTxt** [spenteco/nanogenmo2016#1]
Your project is very interesting. I'm trying to create my own database but I'm running into this error:

python clean_text_folder.py small_corpus

Traceback (most recent call last):
  File "clean_text_folder.py", line 8, in <module>
    N_WORDS_REQUESTED = int(sys.argv[3])
IndexError: list index out of range

Tested on python 2.7 and 3.4 under Ubuntu 16.04 and 14.04

Text files are utf-8, line ending Unix/Linux inside folder "small_corpus"
which is in the same folder as "clean_text_folder.py"

Also, I would like to test your PG database if available.

Thanks

**Comment by spenteco** [comment]
I think you need to pass another argument across the command line.  Try:

./clean_text_folder.py input_folder_name output_file_name 
some_very_large_number

Like:

./clean_text_folder.py mytexts/ my_fasttext_input.txt 999999999

**Comment by GenTxt** [comment]
Thanks. After a few edits everything is working

**Comment by spenteco** [comment]
Cool.  I should have the pg corpus up later today or tomorrow . . . it's 
5.7G, and it's taking a while to upload.

**Comment by spenteco** [comment]
The text files are here:


     http://ada.artsci.wustl.edu/pg/pg_text_files_no_headers.zip

Beware: it's 5.7G compressed . . .

The catalog files are also there:

     http://ada.artsci.wustl.edu/pg/pg_catalog_012615_FINAL.csv
     http://ada.artsci.wustl.edu/pg/pg_catalog_012615_FINAL.ods
